# Site settings
description: >
  Notre métier, créer des sites et applications Web.
  Notre principe, s'adapter en continu aux utilisateurs.
name: Ochelys

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
