# Site settings
title: Ochelys, Prototypage et innovation par les usages
description: >
  Notre métier, créer des sites et applications Web.
  Notre principe, s'adapter en continu aux utilisateurs.

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
