# Site settings
name: Ochelys

collections:
  clients:
  realisations:
    output: true
    defaults:
      values:
        layout: realisation

# Compress CSS output
sass:
  style: compressed

# Live reload options
livereload: true
