# Site settings
name: Ochelys

collections:
  clients:
  realisations:
    output: true
    defaults:
      values:
        layout: realisation

# Compress CSS output
sass:
  style: compressed

# Live reload options
livereload: true

# Prevent compilation of unwanted files and folders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
